using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.XR.Hands;
using UnityEngine.XR.Interaction.Toolkit.Interactables;

namespace Vindolanda.Animation
{
    /// <summary>
    /// Play back a motion-captured animation generated by <see cref="MocapRecorder"/>
    /// Does not handle IK, currently intended for floating head and hand models
    /// 
    /// Quite CPU intensive, use sparingly and consider disabling when not visible
    /// </summary>
    public class MocapPlayer : MonoBehaviour
    {
        public Transform leftHandPosition;
        public GestureRenderer leftHandPose;
        public Transform rightHandPosition;
        public GestureRenderer rightHandPose;
        public Transform head;

        [Header("Playback Settings")] // Not "Player settings" as "Player" is a reserved term for the player of the game
        public Clip clip;
        public bool repeat;
        public float speedMult = 1.0f;

        public Quaternion heldItemRotationOffset = Quaternion.Euler(0, 0, 90);
        [Tooltip("Applied AFTER heldItemRotationOffset")]
        public Vector3 heldItemPositionOffset = Vector3.forward * 0.06f;

        [Header("State")]
        public bool playing;
        public int frame;
        float elapsedTime;

        GameObject leftObject;
        GameObject rightObject;

        GameObject SetHeldObject(GameObject obj, Transform hand, Handedness handedness)
        {
            if (obj == null) return null;
            var instance = Instantiate(obj, parent: hand);
            instance.SetActive(false);

            if (instance.TryGetComponent<XRGrabInteractable>(out var interactable))
            {
                if (interactable.attachTransform != null)
                {
                    var offset = handedness == Handedness.Right ? heldItemRotationOffset : Quaternion.Inverse(heldItemRotationOffset);
                    var inverseRotation = offset * Quaternion.Inverse(interactable.attachTransform.localRotation);
                    var inversePosition = (inverseRotation * -interactable.attachTransform.localPosition) + heldItemPositionOffset;
                    instance.transform.SetLocalPositionAndRotation(inversePosition, inverseRotation);
                }
                interactable.enabled = false;
            }

            if (instance.TryGetComponent<Rigidbody>(out var rb))
            {
                rb.SetFrozen(true);
            }

            return instance;
        }

        private void Start()
        {
            leftObject = SetHeldObject(clip.leftHandItem, leftHandPosition, Handedness.Left);
            rightObject = SetHeldObject(clip.rightHandItem, rightHandPosition, Handedness.Right);
        }

        private void Update()
        {
            if (!playing) return;
            if (clip == null) return;

            elapsedTime += Time.deltaTime * speedMult;
            while (clip.keyframes[frame + 1].startTime < elapsedTime)
            {
                frame++;

                if (frame >= clip.keyframes.Count - 1)
                {
                    frame = 0;
                    elapsedTime = 0;
                    if (!repeat)
                    {
                        playing = false;
                        return;
                    }
                    break;
                }
            }

            Clip.Keyframe current = clip.keyframes[frame];
            Clip.Keyframe next = clip.keyframes[frame + 1];
            float currentFrameDuration = next.startTime - current.startTime;
            float currentFrameElapsed = elapsedTime - current.startTime;

            float ratio = currentFrameElapsed / currentFrameDuration;
            Clip.Keyframe interpolated = Clip.Keyframe.Lerp(current, next, ratio);

            void UpdateHand(Transform hand, Clip.HandState state, Handedness handedness, GameObject held)
            {
                if (hand == null) return;
                hand.SetLocalPositionAndRotation(state.transform.position, state.transform.rotation);

                if (held != null)
                {
                    held.SetActive(state.hasItem);
                }
            }
            UpdateHand(leftHandPosition, interpolated.leftHand, Handedness.Left, leftObject);
            leftHandPose.SetShapeInstant(interpolated.leftHand);
            UpdateHand(rightHandPosition, interpolated.rightHand, Handedness.Right, rightObject);
            rightHandPose.SetShapeInstant(interpolated.rightHand);
            if (head)
                head.SetLocalPositionAndRotation(interpolated.head.position, interpolated.head.rotation);

            if (clip.leftFollowsRight && leftObject != null)
                leftObject.transform.LookAt(rightHandPosition.transform);
            if (clip.rightFollowsLeft && rightObject != null)
                rightObject.transform.LookAt(leftHandPosition.transform);
        }

        private void OnDrawGizmosSelected()
        {
            if (clip == null) return;
            Gizmos.matrix = transform.localToWorldMatrix;
            Handles.matrix = transform.localToWorldMatrix;

            Gizmos.color = Color.red;
            Handles.Label(clip.keyframes[0].head.position, "Head");
            Gizmos.DrawLineStrip(clip.keyframes.Select(kf => kf.head.position).ToArray(), looped: false);
            Gizmos.color = Color.green;
            Handles.Label(clip.keyframes[0].leftHand.transform.position, "Left Hand");
            Gizmos.DrawLineStrip(clip.keyframes.Select(kf => kf.leftHand.transform.position).ToArray(), looped: false);
            Gizmos.color = Color.blue;
            Handles.Label(clip.keyframes[0].rightHand.transform.position, "Right Hand");
            Gizmos.DrawLineStrip(clip.keyframes.Select(kf => kf.rightHand.transform.position).ToArray(), looped: false);
        }
    }
}