using UnityEngine;
using UnityEngine.XR;
using UnityEngine.XR.Hands;
using UnityEngine.XR.Interaction.Toolkit.Interactables;

namespace Vindolanda.Animation
{
    /// <summary>
    /// Play back a motion-captured animation generated by <see cref="MocapRecorder"/>
    /// Does not handle IK, currently intended for floating head and hand models
    /// 
    /// Quite CPU intensive, use sparingly and consider disabling when not visible
    /// </summary>
    public class MocapPlayer : IKDriver
    {
        public GestureRenderer leftHand;
        public GestureRenderer rightHand;
        public Transform head;

        [Header("Playback Settings")] // Not "Player settings" as "Player" is a reserved term for the player of the game
        public Clip clip;
        public bool repeat;
        public float speedMult = 1.0f;

        [Header("State")]
        public bool playing;
        public int frame;
        float elapsedTime;

        GameObject leftObject;
        GameObject rightObject;

        GameObject SetHeldObject(GameObject obj, Transform hand)
        {
            if (obj == null) return null;
            var instance = Instantiate(obj, parent: hand);
            instance.SetActive(false);

            if (instance.TryGetComponent<XRGrabInteractable>(out var interactable))
            {
                if (interactable.attachTransform != null)
                {
                    var inverseRotation = Quaternion.Inverse(interactable.attachTransform.localRotation);
                    var inversePosition = inverseRotation * -interactable.attachTransform.localPosition;
                    instance.transform.SetLocalPositionAndRotation(inversePosition, inverseRotation);
                }
                interactable.enabled = false;
            }

            if (instance.TryGetComponent<Rigidbody>(out var rb))
            {
                rb.SetFrozen(true);
            }

            return instance;
        }

        private void Start()
        {
            leftObject = SetHeldObject(clip.leftHandItem, leftHand.transform);
            rightObject = SetHeldObject(clip.rightHandItem, rightHand.transform);
        }

        void AdvanceAnimation()
        {
            elapsedTime += Time.deltaTime * speedMult;
            while (clip.keyframes[frame + 1].startTime < elapsedTime)
            {
                frame++;

                if (frame >= clip.keyframes.Count - 1)
                {
                    frame = 0;
                    elapsedTime = 0;
                    if (!repeat)
                    {
                        playing = false;
                        return;
                    }
                    break;
                }
            }
        }

        Clip.Keyframe GetInterpolatedFrame()
        {
            Clip.Keyframe current = clip.keyframes[frame];
            Clip.Keyframe next = clip.keyframes[frame + 1];
            float currentFrameDuration = next.startTime - current.startTime;
            float currentFrameElapsed = elapsedTime - current.startTime;

            float ratio = currentFrameElapsed / currentFrameDuration;
            return Clip.Keyframe.Lerp(current, next, ratio);
        }

        private void Update()
        {
            if (!playing) return;
            if (clip == null) return;

            AdvanceAnimation();

            if (head)
            {
                var interpolated = GetInterpolatedFrame();
                head.SetPositionAndRotation(interpolated.head.position, interpolated.head.rotation);
                //PositionBodyFromHead(head.position, (transform.parent.rotation * interpolated.head.rotation).eulerAngles.y);
                PositionBodyFromHead(interpolated.head.position, interpolated.head.rotation.eulerAngles.y);
                //SetPositionAndRotation(
                //    head.localPosition + (Vector3.down * height),
                //    Quaternion.Euler(0, head.localRotation.eulerAngles.y, 0)
                //);
            }
        }

        private void OnAnimatorIK()
        {
            if (!playing) return;
            if (clip == null) return;

            SetIKFootOnGround(AvatarIKGoal.LeftFoot);
            SetIKFootOnGround(AvatarIKGoal.RightFoot);

            var interpolated = GetInterpolatedFrame();

            void UpdateHand(GestureRenderer hand, Clip.HandState state, AvatarIKGoal handedness, GameObject held)
            {
                if (hand == null) return;
                //var offset = handedness == AvatarIKGoal.RightHand ? handOffset : Quaternion.Inverse(handOffset);
                //hand.transform.SetLocalPositionAndRotation(transform.rotation * state.transform.position, state.transform.rotation * offset);
                hand.SetShapeInstant(state);

                if (held != null)
                {
                    held.SetActive(state.hasItem);
                }

                //SetIKPositionAndWeight(handedness, 1.0f,
                //    hand.transform.position, hand.transform.rotation
                //);
                SetIKPositionAndWeight(handedness, 1.0f, state.transform.position, state.transform.rotation);
                hand.transform.position = Animator.GetIKPosition(handedness);
            }
            //UpdateHand(leftHand, interpolated.leftHand, AvatarIKGoal.LeftHand, leftObject);



            //SetLocalIKPositionAndWeight(AvatarIKGoal.LeftHand, 1.0f, interpolated.leftHand.transform.position, interpolated.leftHand.transform.rotation);
            //SetIKPositionAndWeight(AvatarIKGoal.LeftHand, 1.0f, transform.position + (transform.rotation * interpolated.leftHand.transform.position), transform.rotation * interpolated.leftHand.transform.rotation);
            //leftHand.transform.position = Animator.GetIKPosition(AvatarIKGoal.LeftHand);


            //void UpdateHand(GestureRenderer hand, Clip.HandState state, AvatarIKGoal handedness, GameObject held)
            //{
            //    if (hand == null) return;
            //    var offset = handedness == AvatarIKGoal.RightHand ? handOffset : Quaternion.Inverse(handOffset);
            //    hand.transform.SetLocalPositionAndRotation(transform.rotation * state.transform.position, state.transform.rotation * offset);
            //    hand.SetShapeInstant(state);

            //    if (held != null)
            //    {
            //        held.SetActive(state.hasItem);
            //    }

            //    SetIKPositionAndWeight(handedness, 1.0f,
            //        hand.transform.position, hand.transform.rotation
            //    );
            //}

            UpdateHand(leftHand, interpolated.leftHand, AvatarIKGoal.LeftHand, leftObject);
            UpdateHand(rightHand, interpolated.rightHand, AvatarIKGoal.RightHand, rightObject);
            ////head.SetLocalPositionAndRotation



            //Debug.DrawLine(Animator.GetIKPosition(AvatarIKGoal.LeftHand), leftHand.transform.position);
            //print(Vector3.Distance(Animator.GetIKPosition(AvatarIKGoal.LeftHand), leftHand.transform.position));
        }
    }
}