using UnityEngine;

namespace Vindolanda.Mocap
{
    /// <summary>
    /// Play back a motion-captured animation generated by <see cref="MocapRecorder"/>
    /// Does not handle IK, currently intended for floating head and hand models
    /// 
    /// Quite CPU intensive, use sparingly and consider disabling when not visible
    /// </summary>
    public class MocapPlayer : MonoBehaviour
    {
        public GestureRenderer leftHand;
        public GestureRenderer rightHand;
        public Transform head;

        [Header("Playback Settings")] // Not "Player settings" as "Player" is a reserved term for the player of the game
        public Clip clip;
        public bool repeat;
        public float speedMult = 1.0f;

        [Header("State")]
        public bool playing;
        public int frame;
        float elapsedTime;

        private void Update()
        {
            if (!playing) return;
            if (clip == null) return;

            elapsedTime += Time.deltaTime * speedMult;
            while (clip.keyframes[frame + 1].startTime < elapsedTime)
            {
                frame++;

                if (frame >= clip.keyframes.Count - 1)
                {
                    frame = 0;
                    elapsedTime = 0;
                    if (!repeat)
                    {
                        playing = false;
                        return;
                    }
                    break;
                }
            }

            Clip.Keyframe current = clip.keyframes[frame];
            Clip.Keyframe next = clip.keyframes[frame + 1];
            float currentFrameDuration = next.startTime - current.startTime;
            float currentFrameElapsed = elapsedTime - current.startTime;

            float ratio = currentFrameElapsed / currentFrameDuration;
            Clip.Keyframe interpolated = Clip.Keyframe.Lerp(current, next, ratio);

            static void UpdateHand(GestureRenderer hand, Clip.HandState state)
            {
                if (hand == null) return;
                hand.transform.SetLocalPositionAndRotation(state.transform.position, state.transform.rotation);
                hand.SetShapeInstant(state);
            }
            UpdateHand(leftHand, interpolated.leftHand);
            UpdateHand(rightHand, interpolated.rightHand);
            if (head)
                head.SetLocalPositionAndRotation(interpolated.head.position, interpolated.head.rotation);
        }
    }
}